# Site settings
title: String Theory
description: "A game of connections"

# Build settings
markdown: kramdown
permalink: /:title/

# Collections
collections:
  puzzles:
    output: true
    permalink: /:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
